# permissions for end users to view songsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: songsconfig-viewer-role
rules:
- apiGroups:
  - songs.example.com
  resources:
  - songsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - songs.example.com
  resources:
  - songsconfigs/status
  verbs:
  - get
